[package]
name = "wgpu-sandbox"
version = "0.1.0"
authors = ["https://github.com/Davidster/wgpu-sandbox/graphs/contributors"]
edition = "2021"
rust-version = "1.65"
description = "3D renderer that will be used to make a simple first person shooter"
repository = "https://github.com/Davidster/wgpu-sandbox"
license = "MIT"
keywords = ["renderer", "first person shooter", "3D", "rust", "wgpu", "game"]
categories = ["rendering", "game framework", "gamedev"]
publish = false

[features]
default = []
tracy = ["profiling/profile-with-tracy"]
tracy-gpu = ["tracy"]
tracy-alloc = ["tracy"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
half = "2"
pollster = "0.2"
twox-hash = "1.6"

# log
anyhow = { version = "1", features = ["backtrace"] }
console = "0.15"
env_logger = { version = "0.10", default-features = false, features = ["auto-color", "humantime"] }
log = "0.4"
profiling = "1.0.7" # The version better be the one used by wgpu-core/hal

# assets
gltf = "1"
image = { version = "0.23.14", default-features = false, features = ["hdr", "jpeg"] } # The version better be the one used by gltf crate
obj-rs = "0.7"
wavefront_obj = "10"

# surface
wgpu = "0.14"
winit = "0.27"

# math
cgmath = "0.18"
rand = "0.8"
rapier3d = "0.16"

# audio
cpal = "0.14"
hound = "3"
minimp3 = "0.5"
oddio = "0.6"

[profile.dev.package."*"]
opt-level = 3

# [profile.release]
# codegen-units = 1