[workspace]
resolver = "2"
members = ["ikari", "build_web", "example_game", "clikari"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.66"
description = "3D Game Engine"
keywords = ["renderer", "3D", "rust", "wgpu", "game"]
license = "MIT"
repository = "https://github.com/Davidster/ikari"
categories = ["rendering", "game framework", "gamedev"]
authors = [
  "David Huculak https://github.com/Davidster",
  "Ikari Contributors https://github.com/Davidster/ikari/graphs/contributors",
]

[workspace.dependencies]
winit = { version = "0.27", git = "https://github.com/iced-rs/winit.git", rev = "940457522e9fb9f5dac228b0ecfafe0138b4048c" }
ikari = { version = "0.0.1", path = "./ikari" }
log = "0.4"
wgpu = "0.16"
anyhow = { version = "1.0", features = ["backtrace"] }
env_logger = { version = "0.10", default-features = false, features = [
  "auto-color",
  "humantime",
] }
# The version should be the one used by wgpu-core/hal TODO: does this version number need updating?
profiling = "1.0.8"
image = { version = "0.24", default-features = false, features = [
  "hdr",
  "jpeg",
] }
gltf = "1.2"
pico-args = "0.5.0"
lazy_static = "1.4"

# wasm32 depdendencies
web-sys = { version = "0.3.64", features = [
  "Document",
  "Window",
  "Element",
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Blob",
  "WorkerGlobalScope",
] }
wasm-bindgen = { version = "0.2.87", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.37"

[patch.crates-io]
iced_native = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced_graphics = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced_style = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
# iced_native = { path = "../iced-fork/native" }
# iced_graphics = { path = "../iced-fork/graphics" }
# iced_style = { path = "../iced-fork/style" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."wgpu-core"]
debug-assertions = false

# [profile.dev.package."wgpu"]
# debug-assertions = false

# [profile.dev.package."wgpu-hal"]
# debug-assertions = false

# [profile.dev.package."wgpu-types"]
# debug-assertions = false

[profile.release]
debug = true
