[package]
name = "ikari"
version = "0.1.0"
authors = [
    "David Huculak https://github.com/Davidster",
    "Ikari Contributors https://github.com/Davidster/ikari/graphs/contributors",
]
edition = "2021"
rust-version = "1.66"
description = "3D renderer that will be used to make a simple first person shooter"
repository = "https://github.com/Davidster/ikari"
license = "MIT"
keywords = ["renderer", "first person shooter", "3D", "rust", "wgpu", "game"]
categories = ["rendering", "game framework", "gamedev"]
publish = false

[lib]
name = "ikari"
path = "src/lib.rs"

[[bin]]
name = "example_game"
path = "src/example_game/main.rs"

[[bin]]
name = "asset_optimizer"
path = "src/asset_optimizer/main.rs"

[[bin]]
name = "audio_decoder_perf"
path = "src/audio_decoder_perf/main.rs"

[features]
default = []
#Not supported at this time #profile-with-optick = ["profiling/profile-with-optick"]
#Not supported at this time #profile-with-superluminal = ["profiling/profile-with-superluminal"]
#Not supported at this time #profile-with-tracing = ["profiling/profile-with-tracing"]
tracy = ["profiling/profile-with-tracy"]
tracy-n-alloc = ["tracy"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
half = "2"
pollster = "0.3"
twox-hash = "1.6"
lazy_static = "1.4"
smallvec = { version = "1.10", features = ["union", "const_generics"] }
anyhow = { version = "1.0", features = ["backtrace"] }
threadpool = "1.8.1"
walkdir = "2.3.3"
num_cpus = "1.15.0"

# log
console = "0.15"
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
log = "0.4"

# profiling
profiling = "1.0.7"      # The version should be the one used by wgpu-core/hal
wgpu-profiler = "0.11.0"

# assets
gltf = "1.1"
image = { version = "0.23.14", default-features = false, features = [
    "hdr",
    "jpeg",
] } # The version should be the one used by gltf crate
obj-rs = "0.7"
wavefront_obj = "10.0"
basis-universal = "0.2.0"
zstd = "0.12.3"

# rendering
wgpu = "0.15"
winit = { version = "0.27", git = "https://github.com/iced-rs/winit.git", rev = "940457522e9fb9f5dac228b0ecfafe0138b4048c" }

# math
rand = "0.8"
rapier3d = "0.17"
glam = { version = "0.23.0", features = ["approx", "bytemuck"] }
approx = "0.5"

# audio
cpal = "0.15"
# hound = "3"
# minimp3 = "0.5"
oddio = "0.6"
symphonia = { version = "0.5.2", features = ["mp3", "wav"] }

# UI
iced_wgpu = { git = "https://github.com/Davidster/iced.git", branch = "wgpu_15" }
iced = { git = "https://github.com/Davidster/iced.git", branch = "wgpu_15" }
iced_winit = { git = "https://github.com/Davidster/iced.git", branch = "wgpu_15" }
plotters-iced = "0.7"
plotters = { version = "0.3", default_features = false, features = [
    "line_series",
] }

[patch.crates-io]
iced_native = { git = "https://github.com/Davidster/iced.git", branch = "wgpu_15" }
iced_graphics = { git = "https://github.com/Davidster/iced.git", branch = "wgpu_15" }

[profile.dev.package."basis-universal-sys"]
opt-level = 3

[profile.release]
#debug = true
# incremental = false
# codegen-units = 1
debug = true
