[package]
name = "ikari"
version = "0.1.0"
authors = [
    "David Huculak https://github.com/Davidster",
    "Ikari Contributors https://github.com/Davidster/ikari/graphs/contributors"
]
edition = "2021"
rust-version = "1.65"
description = "3D renderer that will be used to make a simple first person shooter"
repository = "https://github.com/Davidster/ikari"
license = "MIT"
keywords = ["renderer", "first person shooter", "3D", "rust", "wgpu", "game"]
categories = ["rendering", "game framework", "gamedev"]
publish = false

[features]
default = []
#Not supported at this time #profile-with-optick = ["profiling/profile-with-optick"]
#Not supported at this time #profile-with-superluminal = ["profiling/profile-with-superluminal"]
#Not supported at this time #profile-with-tracing = ["profiling/profile-with-tracing"]
profile-with-tracy = ["profiling/profile-with-tracy"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
half = "2"
pollster = "0.2"
twox-hash = "1.6"
lazy_static = "1.4.0"
smallvec = { version = "1.10.0", features = ["union", "const_generics"] }

# log
anyhow = { version = "1", features = ["backtrace"] }
console = "0.15"
env_logger = { version = "0.10", default-features = false, features = ["auto-color", "humantime"] }
log = "0.4"

# profile
profiling = "1.0.7" # The version should be the one used by wgpu-core/hal

# assets
gltf = "1"
image = { version = "0.23.14", default-features = false, features = ["hdr", "jpeg"] } # The version should be the one used by gltf crate
obj-rs = "0.7"
wavefront_obj = "10"

# surface
wgpu = "0.14"
winit = "0.27"

# math
rand = "0.8"
rapier3d = "0.16"
glam = { version = "0.22.0", features = ["approx", "bytemuck"] }
approx = "0.5.1"

# audio
cpal = "0.14"
hound = "3"
minimp3 = "0.5"
oddio = "0.6"

[profile.dev]
opt-level = 0

[profile.release]
incremental = false
codegen-units = 1
debug = true
