[package]
name = "wgpu-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.52", features = ["backtrace"] }
image = "0.23.14"
stb = { version = "0.3.2" }
half = "1.8.2"
obj-rs = "0.7.0"
wavefront_obj = "10.0.0"
wgpu = "0.13"
winit = "0.26.1"
log = "0.4"
pollster = "0.2.5"
env_logger = "0.9.0"
bytemuck = { version = "1.7.3", features = [ "derive" ] }
cgmath = "0.18.0"
console = "0.15.0"
dialoguer = "0.10.0"
rand = "0.8.5"
gltf = "1.0.0"
rapier3d = "0.13.0"

[profile.dev.package."*"]
opt-level = 3

# [profile.release]
# codegen-units = 1