[workspace]
resolver = "2"
members = ["ikari", "build_web", "example_game", "clikari"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.88"
description = "3D Game Engine"
keywords = ["renderer", "3D", "rust", "wgpu", "game"]
license = "MIT"
repository = "https://github.com/Davidster/ikari"
categories = ["rendering", "game framework", "gamedev"]
authors = [
  "David Huculak https://github.com/Davidster",
  "Ikari Contributors https://github.com/Davidster/ikari/graphs/contributors",
]

[workspace.dependencies]
winit = "0.30"
ikari = { version = "0.0.1", path = "./ikari", default-features = false }
log = "0.4"
wgpu = { version = "27.0", features = ["serde"] }
wgpu-profiler = "0.25.0"
anyhow = { version = "1.0", features = ["backtrace"] }
env_logger = { version = "0.11", default-features = false, features = [
  "auto-color",
  "humantime",
] }
profiling = "1.0"
image = { version = "0.25", default-features = false, features = [
  "hdr",
  "jpeg",
  "png",
] }
gltf = "1.4"
pico-args = "0.5.0"
lazy_static = "1.5"
glam = { version = "0.28", features = ["approx", "bytemuck"] }
rand = { version = "0.8", features = ["small_rng"] }
pollster = "0.3"

# wasm32 depdendencies
web-sys = { version = "0.3.64", features = [
  "Document",
  "Window",
  "Element",
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Blob",
  "WorkerGlobalScope",
  "Url",
  "ReadableStream",
  "ReadableStreamDefaultReader",
  "HtmlCollection",
] }
wasm-bindgen = { version = "0.2.127", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.42"

iced = { version = "0.14", features = ["canvas"] }
iced_wgpu = "0.14"
iced_winit = "0.14"

[profile.dev]
opt-level = 1
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
