[workspace]
resolver = "2"
members = ["ikari", "build-web"]
default-members = ["ikari"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.66"
description = "3D Game Engine"
keywords = ["renderer", "3D", "rust", "wgpu", "game"]
license = "MIT"
repository = "https://github.com/Davidster/ikari"
categories = ["rendering", "game framework", "gamedev"]
authors = [
  "David Huculak https://github.com/Davidster",
  "Ikari Contributors https://github.com/Davidster/ikari/graphs/contributors",
]

[patch.crates-io]
iced_native = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced_graphics = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced_style = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
# iced_native = { path = "../iced-fork/native" }
# iced_graphics = { path = "../iced-fork/graphics" }
# iced_style = { path = "../iced-fork/style" }

[profile.dev.package."basis-universal-sys"]
opt-level = 3

[profile.release]
# debug = true
# incremental = false
# codegen-units = 1
debug = true
