[package]
name = "wgpu-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytemuck = { version = "1", features = ["derive"] }
console = "0.15"
env_logger = { version = "0.10", default-features=false, features = ["auto-color", "humantime"] }
half = "2"
log = "0.4"
pollster = "0.2"
puffin = "0.14"
puffin_http = "0.11"

# assets
gltf = "1"
image = "0.24"
obj-rs = "0.7"
stb = "0.3"
wavefront_obj = "10"

# surface
wgpu = "0.14"
winit = "0.27"

# math
cgmath = "0.18"
rand = "0.8"
rapier3d = "0.15"

# audio
cpal = "0.14"
hound = "3"
minimp3 = "0.5"
oddio = "0.6"

[profile.dev.package."*"]
opt-level = 3

# [profile.release]
# codegen-units = 1