[package]
name = "ikari"
version.workspace = true
edition.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[lib]
name = "ikari"
path = "src/lib.rs"

[features]
default = []
tracy = ["profiling/profile-with-tracy", "dep:tracing-tracy"]
tracy-n-alloc = []

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
half = { version = "2.3.1" }
pollster = "0.3"
twox-hash = "1.6"
lazy_static = "1.4"
smallvec = { version = "1.11", features = ["union", "const_generics"] }
anyhow.workspace = true
chrono = { version = "0.4.26", default-features = false, features = [
    "std",
    "wasmbind",
    "clock",
] }
instant = "0.1.12"
async-std = "1.12.0"

# log
console = "0.15"
env_logger.workspace = true
log.workspace = true

# profiling
# The version should be the one used by wgpu-core/hal TODO: does this version number need updating?
profiling.workspace = true
wgpu-profiler = "0.12"
# wgpu-profiler = { path = "../../wgpu-profiler-fork" }
tracing-tracy = { version = "0.10.2", features = ["ondemand"], optional = true }

# assets
gltf.workspace = true
image.workspace = true
obj-rs = "0.7"
wavefront_obj = "10.0"

# rendering
wgpu.workspace = true
# wgpu = { path = "../../wgpu/wgpu" }
winit.workspace = true

# math
rand = { version = "0.8", features = ["small_rng"] }
rapier3d = "0.17"
glam = { version = "0.24.1", features = ["approx", "bytemuck"] }
approx = "0.5"

# audio
cpal = { git = "https://github.com/DouglasDwyer/cpal.git", rev = "91aeb4d" }
oddio = "0.6"
symphonia = { version = "0.5.3", features = ["mp3", "wav"] }

# UI
iced_wgpu = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
iced_winit = { git = "https://github.com/Davidster/iced.git", branch = "no_webgl" }
# iced_wgpu = { path = "../../iced-fork/wgpu", default-features = false, features = [
# ] }
# iced = { path = "../../iced-fork" }
# iced_winit = { path = "../../iced-fork/winit" }

plotters-iced = "0.8"
plotters = { version = "0.3", default-features = false, features = [
    "line_series",
] }
iced_aw = { git = "https://github.com/iced-rs/iced_aw.git", branch = "main", default-features = false, features = [
    "modal",
    "card",
] }
wasm_thread = { version = "0.2.0", features = ["es_modules"] }
futures-intrusive = "0.5.0"
rmp-serde = "1.1.2"
serde = "1.0.173"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
basis-universal = "0.3.0"
zstd = "0.12.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.64"
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
getrandom = { version = "0.2.10", features = ["js"] }
serde = "1.0.173"
serde_derive = "1.0.173"
wasm-bindgen.workspace = true
cpal = { git = "https://github.com/DouglasDwyer/cpal.git", rev = "91aeb4d", features = [
    "wasm-bindgen",
] }
