[alias]
build-web = "run --release --package build-web --"

# [target.'cfg(target_arch = "wasm32")']
# rustflags = [
#   "--cfg=web_sys_unstable_apis",
#   "-C",
#   "target-feature=+atomics,+bulk-memory,+mutable-globals",
# ]

# [target.wasm32-unknown-unknown]
# rustflags = [
#   "--cfg=web_sys_unstable_apis",
#   "-C",
#   "target-feature=+atomics,+bulk-memory,+mutable-globals",
# ]

# [unstable]
# build-std = ["panic_abort", "std"]
