[alias]
run-wasm = "run --release --package run-wasm --"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[unstable]
build-std = ['std', 'panic_abort']

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]
